project:
  type: website
  output-dir: docs

website:
  title: "A gene's eye view to inbreeding"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
      theme: Minty
      max-width: 1800px
      toc: true
      toc-location: left
      code-fold: true
      smooth-scroll: true